platform :ios, '8.0'
use_frameworks!

target 'OAuth-Moya-Promise_Example' do
  pod 'OAuth-Moya-Promise', :path => '../'
end

target 'OAuth-Moya-Promise_Tests' do
	pod 'OAuth-Moya-Promise', :path => '../'
	pod 'Quick', '~> 1.0.0'
	pod 'Nimble', '~> 5.1.1'
end
